export const ERROR_CODES = {
  // Auth
  INVALID_PHONE: 'INVALID_PHONE',
  INVALID_CODE: 'INVALID_CODE',
  CODE_EXPIRED: 'CODE_EXPIRED',
  TOO_MANY_ATTEMPTS: 'TOO_MANY_ATTEMPTS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Conversation
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  NOT_A_PARTICIPANT: 'NOT_A_PARTICIPANT',
  NOT_AN_ADMIN: 'NOT_AN_ADMIN',
  ALREADY_EXISTS: 'ALREADY_EXISTS',

  // Message
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
  EMPTY_MESSAGE: 'EMPTY_MESSAGE',

  // Transport
  TRANSPORT_UNAVAILABLE: 'TRANSPORT_UNAVAILABLE',
  WS_CONNECTION_FAILED: 'WS_CONNECTION_FAILED',

  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
